### ISSUE TITLE
Add ability to render error message when running the login command

### ISSUE THREAD

**Issue by iamkirkbater** [clcollins/srepd#79]
Today I had an issue where I hadn't started my podman machine (a necessary step for podman to work on MacOS) and therefore the login command I have setup was failing. In my personal setup I have srepd opening up a new tmux window in my current session and then running ocm-container with automatic login to that cluster. Because of the tmux setup, when the ocm-container command exits the tmux window also closes. This causes me to lose any access to the error messages that happened.

So this morning when I tried to log into a cluster from SREPD, it would flash the new tmux window and then immediately exit back to srepd. Originally I thought this would be an SREPD error, but when I went to just open it up manually I found the issue.

While I think that in the general sense this is out of scope for SREPD, some kind of indicator that the login command exited with a non-0 status may have indicated to me that there was an issue outside of SREPD's control that SREPD is just relaying to me.

I also understand this is very specific to my use case, as if I just had it launch a whole new window the information would probably have persisted and I would have been able to see it, but where I do think this kind of "feature" would add value would be preventing future users from thinking that SREPD is the cause of the issue when it's something outside of srepd's control.

**Comment by clcollins** [comment]
I don't think we can fix this in SREPD - the launcher collects a TON of error output and routes them to error messages (and I've validated it works), but terminal programs (at least the ones I have tested) do not provide stderr/stdout for commands running inside of them, or at all.  That makes sense when you think about how terminals are launched usually, I think.

I have had this happen before too, and have been able to troubleshoot by telling gnome-terminal to not exit when the command exits (in gnome-terminal's preferences), and it will show me the errors and it's own errors inside the terminal program, but won't write them back to a CLI (or SREPD) when I'm forcing errors.

For troubleshooting, I setup a separate terminal profile "noexit" and told it not to exit, and then changed my `terminal` command in the config to `gnome-terminal --profile=noexit` and could see, eg: where podman wasn't liking the way a command was parsed, etc.  I then reverted the `--profile=noexit` when I fixed it, so I didn't need to manually close the terminal myself every time ocm-container exits.

**Comment by clcollins** [comment]
I'm going to close this, but if you think it needs to re-open, just ping me!  Thanks!

**Comment by iamkirkbater** [comment]
Thanks for the explanation Chris! Since you've already investigated this a bit I think we can keep this closed. 

Maybe I can add a docs entry tomorrow to the README to potentially add some troubleshooting help there, but what you said entirely makes sense.
